extraction:
  cpp:
    prepare:
      packages:
        - libjansson-dev
        - libc6-dev
        - g++-10
    configure:
      command:
        - mkdir _lgtm_build_dir
        - cd _lgtm_build_dir
        - cmake -DBUILD_GTEST=OFF -DINSTALL_GTEST=OFF ..
    index:
      build_command:
        - cd _lgtm_build_dir
        - make
